### ISSUE TITLE
Unable to deploy on harmony testnet

### ISSUE THREAD

**Issue by HYDEAI** [polymorpher/one-wallet#149]
Hi, I'm trying to deploy:
https://github.com/polymorpher/one-wallet/commit/9e110f34616fc2bb323b4e4bbb37372bbf747e6a

to harmony testnet,
using this command:
`truffle migrate  --network harmony-testnet --reset`

but I get an error:

`Error: Invalid number of parameters for "undefined". Got 0 expected 4!`
```
RuntimeError: abort(Error: Invalid number of parameters for "undefined". Got 0 expected 4!). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/Users/xxxxxxxx/.config/truffle/compilers/node_modules/soljson-v0.8.4+commit.c7e474f2.js:1:12950)
    at process.emit (events.js:223:5)
    at process.emit (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/source-map-support/source-map-support.js:495:1)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:32)
```

I modified my 01_libraries.js to the following as it says I need to deploy and link other libraries:

```
const ONEWallet = artifacts.require('ONEWallet')
const DomainManager = artifacts.require('DomainManager')
const TokenTracker = artifacts.require('TokenTracker')
const WalletGraph = artifacts.require('WalletGraph')
const CommitManager= artifacts.require('CommitManager')
const SignatureManager= artifacts.require('SignatureManager')
const SpendingManager= artifacts.require('SpendingManager')


async function doDeploy(deployer) {
   await deployer.deploy(CommitManager)
   await deployer.deploy(SignatureManager)
   await deployer.deploy(SpendingManager)
   await deployer.link(CommitManager, ONEWallet);
   await deployer.link(SignatureManager, ONEWallet);
   await deployer.link(SpendingManager, ONEWallet);
   await deployer.deploy(DomainManager)
   await deployer.deploy(TokenTracker)
   await deployer.link(DomainManager, WalletGraph);
   await deployer.deploy(WalletGraph)
   await deployer.link(DomainManager, ONEWallet);
   await deployer.link(TokenTracker, ONEWallet);
   await deployer.link(WalletGraph, ONEWallet);
   await deployer.deploy(ONEWallet)
}

module.exports = function (deployer) {
   deployer.then(async()=>{
      await doDeploy(deployer)
   })
}
```

**Comment by polymorpher** [comment]
You need to provide constructor arguments. See relayer/index.js on how it is done. Tests are a bit outdated.

**Comment by HYDEAI** [comment]
Hi @polymorpher, thanks for your help, figure it out.  It was my misunderstanding of how the wallet works.
The wallet is the smart contract, so I've been deploying plenty of times now.

No need to deploy it via truffle... at least it's not set up to be.  Closing this now.
